# Generated by Django 5.0.6 on 2024-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_crea',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
    ]
