# Generated by Django 5.0.6 on 2024-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_persona_fecha_crea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='nuevosproductos')),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_crea',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AddField(
            model_name='persona',
            name='rut',
            field=models.CharField(default='default_rut', max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
