# Generated by Django 5.0.6 on 2024-06-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contraseña',
            field=models.CharField(default='default_password', max_length=20),
            preserve_default=False,
        ),
    ]
