# Generated by Django 5.0.6 on 2024-06-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_persona_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='username',
            field=models.CharField(default='default username', max_length=12),
            preserve_default=False,
        ),
    ]
