# Generated by Django 5.0.6 on 2024-06-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_persona_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
