# Generated by Django 5.0.6 on 2024-07-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_remove_pedido_productos_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_maxima',
            field=models.IntegerField(default=10),
        ),
    ]
